export const CommongridData:any []=[
    {
        
        "EntityTypeId": 91,
        "CaseId": "AGN0000001",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM24=",
        "DataAreaId": "Mawarid",
        "RecId": 1,
        "AgentName": "Aroop Manpower services ",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "Mahi",
        "ContactMobileNumber": "92 3005791385",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "aroopmps2@gmail.com",
        "Website": "",
        "LicenseNumber": "4162",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 92,
        "CaseId": "AGN0000002",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM28=",
        "DataAreaId": "Mawarid",
        "RecId": 2,
        "AgentName": "Mint International OEPL NO.1689/RWP",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "Ghazala Parveen ",
        "ContactMobileNumber": "91 8130744141",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "arm@hrinternational.in",
        "Website": "",
        "LicenseNumber": "1689/RWP",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 93,
        "CaseId": "AGN0000003",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3A=",
        "DataAreaId": "Mawarid",
        "RecId": 3,
        "AgentName": "Pak Bolan International OEP Lic 1745/Kar",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "Sardar M. Ishaq Khan",
        "ContactMobileNumber": "592653287",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "pakbolanintl@gmail.com",
        "Website": "",
        "LicenseNumber": "1745/Kar",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 94,
        "CaseId": "AGN0000004",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3E=",
        "DataAreaId": "Mawarid",
        "RecId": 4,
        "AgentName": "Sahou Manpower Govt Licence 3295",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "Sana Yaseen",
        "ContactMobileNumber": "92 3174015028",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "misssanayaseen@gmail.com",
        "Website": "",
        "LicenseNumber": "3295",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 95,
        "CaseId": "AGN0000005",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3I=",
        "DataAreaId": "Mawarid",
        "RecId": 5,
        "AgentName": "TRF recruitment lic. 1689/RWP",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "Amina Almas",
        "ContactMobileNumber": "92 3122228722",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "amna.abbasi@hotmail.com",
        "Website": "",
        "LicenseNumber": "1689/RWP",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 98,
        "CaseId": "AGN0000006",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3M=",
        "DataAreaId": "Mawarid",
        "RecId": 6,
        "AgentName": "M/s Self Reliance License No: MPD/1926/RWP",
        "Country": "Pakistan",
        "City": "",
        "ContactPerson": "waheed hafeez",
        "ContactMobileNumber": "557728386",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "selfreliance2012@gmail.com",
        "Website": "",
        "LicenseNumber": "MPD/1926/RWP",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "166",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 98,
        "CaseId": "AGN0000007",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3Q=",
        "DataAreaId": "Mawarid",
        "RecId": 7,
        "AgentName": "HR INTERNATIONAL",
        "Country": "India",
        "City": "",
        "ContactPerson": "Ghazala Parveen ",
        "ContactMobileNumber": "91 8130744141",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "arm@hrinternational.in",
        "Website": "",
        "LicenseNumber": " B-0377/DEL/PER/1000+/5/8398/2009",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "2",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 98,
        "CaseId": "AGN0000008",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3s=",
        "DataAreaId": "Mawarid",
        "RecId": 8,
        "AgentName": "AL SOFI",
        "Country": "India",
        "City": "",
        "ContactPerson": "Farheen",
        "ContactMobileNumber": "91 8082016972",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "farheen@alsofijobs.com",
        "Website": "",
        "LicenseNumber": " B-0006/MUM/PER/1000+/058152/2008",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "2",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 98,
        "CaseId": "AGN0000009",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM3w=",
        "DataAreaId": "Mawarid",
        "RecId": 9,
        "AgentName": "ACCESS PARTNER ",
        "Country": "India",
        "City": "",
        "ContactPerson": "Aafeen Rakhangi",
        "ContactMobileNumber": "9.19005E+11",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "aafeen@accesspar.com",
        "Website": "",
        "LicenseNumber": " 682/MUM/PER/1000+/5/6821/2004",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "2",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    },
    {
        
        "EntityTypeId": 98,
        "CaseId": "AGN0000010",
        "CreatedDatetime": "2023-01-23T16:42:18.487",
        "CreatedBy": "r.admin",
        "ModifiedDatetime": null,
        "ModifiedBy": null,
        "RecVersion": "AAAAAAADM30=",
        "DataAreaId": "Mawarid",
        "RecId": 10,
        "AgentName": "NASSER OVERSEAS",
        "Country": "India",
        "City": "",
        "ContactPerson": "Ayaz Nasser",
        "ContactMobileNumber": "+91 98202 89702",
        "TelephoneNumber": "",
        "FaxNumber": "",
        "Street": "",
        "POBOXNumber": "",
        "PostalCode": "",
        "Email": "ayaz@nassers.org",
        "Website": "",
        "LicenseNumber": "304/Bom/Per/1000+/5/263/84",
        "ContactAddress": "",
        "Notes": null,
        "AgentStatus": null,
        "CityName": null,
        "BankName": "",
        "BranchName": "",
        "BankAccountName": "",
        "BankAccountNo": "",
        "SWIFTCode": "",
        "IBAN": "",
        "CRMAgentCode": null,
        "CRMID": null,
        "InviteStatus": null,
        "TokenID": null,
        "LoginStatus": null,
        "AgentId": null,
        "Content": null,
        "CountryId": "2",
        "CityId": null,
        "IsActive": true,
        "Activate": null,
        "DeActivate": null,
        "ERPAgentId": null,
        "State": null
    }


];